# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20170730_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='category',
            field=models.CharField(default=None, max_length=270),
        ),
    ]
